# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('UPDATE', 'update')], default='update', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
