# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_auto_20151210_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
    ]
